### ISSUE TITLE
"bash: -p: command not found" message when login with ssh, then disconnect

### ISSUE THREAD

**Issue by Qprq** [YunoHost-Apps/wetty_ynh#13]
### Describe the bug

When using the app with my usual username/password, the app outputs the message "bash: -p: command not found", then "Connection to HOSTNAME closed."

### Context

- Hardware: VPS bought online / Dedicated server
- YunoHost version: 4.2.7
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using package version/branch: 2.0.3~ynh6

### Steps to reproduce

- Click on the app tile in the YunoHost portal
- Enter name
- Enter password

### Workaroud

- Edit '/var/www/wetty/config.json5'
- add the line `config:	'/etc/ssh/ssh_config',` just bellow the line `// config:  '/home/user/.wetty_ssh_config',`

**Comment by lordvalium** [comment]
@Qprq  that workaround did not help for me

**Comment by Salamandar** [comment]
@lordvalium @Qprq  Did the new version fix this ?
