### ISSUE TITLE
/usr/bin/env: ‘node’: No such file or directory

### ISSUE THREAD

**Issue by kuba-orlik** [YunoHost-Apps/wetty_ynh#16]
When running the app, the terminal is showing an error

```
/usr/bin/env: ‘node’: No such file or directory
```

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.2.8.3
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 2.0.3~ynh6

**Comment by Salamandar** [comment]
Do you mean the app is installing fine but you got the error on the web page ? Hmm… That's weird. I'll look into it.

**Comment by kuba-orlik** [comment]
Yes, that's what's going on

**Comment by Salamandar** [comment]
@kuba-orlik Did you update ? The issue was upstream and it lokos like it was fixed.
