### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by gwlegion** [YunoHost-Apps/wetty_ynh#22]
### Describe the bug

can't install the application, return an error

### Context

- Hardware: Raspberry Pi at home 
- YunoHost version: Propulsé par [YunoHost](https://yunohost.org/) 11.0.9.13 (stable)
- I have access to my server: Through SSH | through the webadmin 
- Using, or trying to install package version/branch: stable

### Steps to reproduce
just tryed installation with the webadmin

### Logs

https://paste.yunohost.org/raw/egakarumiv

**Comment by Salamandar** [comment]
OK, this is an issue for all apps using this kind of config. Looks like an update to nginx broke this. I'll fix it asap.
